data_ingestion:
  source_path:
  raw_data_path:
  train_data_path:
  test_data_path:
  test_size: 0.2
  random_state: 42

model_training:
  image_width: 244
  image_height: 244
  batch_size: 32
  num_class: 90
  epochs: 3
  fine_tuning_epochs: 10
  lr: 1e-5
  save_path: artifacts/model_training